// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('sample', []);
x$.controller('sample', ['$scope', '$http'].concat(function($scope, $http){
  var data;
  data = {
    children: [
      {
        name: 'China',
        value: 1369460000
      }, {
        name: 'India',
        value: 1270200000
      }, {
        name: 'United States',
        value: 320858000
      }, {
        name: 'Indonesia',
        value: 252164800
      }, {
        name: 'Brazil',
        value: 204210000
      }, {
        name: 'Pakistan',
        value: 189598000
      }, {
        name: 'Nigeria',
        value: 173615000
      }, {
        name: 'Bangladesh',
        value: 158217000
      }, {
        name: 'Russia',
        value: 146068400
      }, {
        name: 'Japan',
        value: 127130000
      }
    ]
  };
  return $http({
    url: 'default.json',
    method: 'GET'
  }).success(function(palettes){
    var pack, nodes, x$, y$;
    $scope.palettes = palettes;
    $scope.palette = $scope.palettes[0];
    pack = d3.layout.pack().size([800, 400]);
    nodes = pack.nodes(data).filter(function(it){
      return it.parent;
    });
    $scope.updateColor = function(){
      $scope.color = d3.scale.ordinal().range($scope.palette.palette);
      return d3.select('#svg').selectAll('circle').attr({
        fill: function(it){
          return $scope.color(it.name);
        }
      });
    };
    $scope.$watch('palette', $scope.updateColor);
    x$ = d3.select('#svg').selectAll('circle').data(nodes);
    x$.enter().append('circle');
    x$.exit().remove();
    $scope.updateColor();
    y$ = d3.select('#svg').selectAll('circle');
    y$.attr({
      cx: function(it){
        return it.x;
      },
      cy: function(it){
        return it.y;
      },
      r: function(it){
        return it.r;
      },
      fill: function(it){
        return $scope.color(it.name);
      },
      stroke: '#999',
      "stroke-width": '2'
    });
    return y$;
  });
}));