// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('color', []);
x$.controller('coloreditor', ['$scope'].concat(function($scope){
  var name, noun, randomColors, res$, i$, i;
  $scope.tags = ['anime', 'nature', 'item', 'movie', 'festival', 'brand'];
  name = ['Barker', 'Stokes', 'Rhodes', 'Salazar', 'Ellis', 'Bradley', 'Sharp', 'Hogan', 'Harvey', 'Briggs'];
  noun = ['Armenian', 'Citizenship', 'Cloud', 'Community', 'Dinghy', 'Jump', 'Pail', 'Passbook', 'Thing', 'Wasp', 'Century', 'Cherry', 'Deficit', 'Editorial', 'Hub', 'Hydrogen', 'Pelican', 'Puppy', 'Snowboarding', 'Wave'];
  randomColors = function(){
    var ret, primarySize, count, i$, i, c;
    ret = [];
    primarySize = 20;
    count = parseInt(Math.random() * 10 + 3);
    for (i$ = 1; i$ <= count; ++i$) {
      i = i$;
      c = {
        h: parseInt(Math.random() * 360),
        s: parseInt(Math.random() * 100),
        l: parseInt(Math.random() * 100)
      };
      c = tinycolor(c);
      c.width = (100 - primarySize) / count;
      ret.push(c);
    }
    ret[parseInt(Math.random() * ret.length)].width = 20 + (100 - primarySize) / count;
    ret.name = name[parseInt(Math.random() * name.length)] + " / " + noun[parseInt(Math.random() * noun.length)];
    return ret;
  };
  res$ = [];
  for (i$ = 0; i$ <= 100; ++i$) {
    i = i$;
    res$.push(randomColors());
  }
  $scope.pals = res$;
  return $scope.featurePals = (function(){
    var i$, results$ = [];
    for (i$ = 1; i$ <= 5; ++i$) {
      i = i$;
      results$.push(randomColors());
    }
    return results$;
  }());
}));