// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('color', []);
x$.controller('coloreditor', ['$scope'].concat(function($scope){
  $scope.pal = [];
  $scope.cur = {
    h: 0,
    s: 0,
    l: 0
  };
  $scope.makecolor = function(h, s, l){
    return tinycolor({
      h: h,
      s: s,
      l: l
    });
  };
  return $scope.add = function(){
    var c;
    c = $scope.makecolor($scope.cur.h, $scope.cur.s, $scope.cur.l);
    console.log(c, c.toHexString());
    return $scope.pal.push(c);
  };
}));